In [9]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census
import gmaps
api_key =  "53187ce5c746ac13e4ec0e9b30e2986f54a82431" 
# Census & gmaps API Keys
#from config import (api_key, gkey)
c = Census(api_key, year=2016)

# Configure gmaps
#gmaps.configure(api_key=gkey)

In [ ]:
#test zip_codes=(60601, 60602, 60603, 60604, 60605, 60606)

In [16]:
# Run Census Search to retrieve data on all zip codes (2016 ACS5 Census)
# See: https://github.com/CommerceDataService/census-wrapper for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
census_data = c.acs5.get(("NAME", 
                          "B01003_001E", 
                          "B01003_001M",
                          "B19013_001E",
                          "B01002_001E",
                          "B19301_001E",
                          "B17001_002E", 
                          "B08133_001E", 
                          "B08008_004E", 
                          "B08006_002E",
                          "B08006_008E",
                          "B08006_014E",
                          "B08006_015E",
                          "B08006_017E",
                          "B06010_011E",
                          "B01001_003E",
                          "B01001_004E",
                          "B01001_005E",
                          "B01001_006E",
                          "B01001_007E",
                          "B01001_008E",
                          "B01001_009E",
                          "B01001_010E",
                          "B01001_011E",
                          "B01001_012E",
                          "B01001_013E",
                          "B01001_014E",
                          "B01001_015E",
                          "B01001_016E",
                          "B01001_017E",
                          "B01001_018E",
                          "B01001_019E",
                          "B01001_020E",
                          "B01001_021E",
                          "B01001_022E",
                          "B01001_023E",
                          "B01001_024E",
                          "B01001_025E",
                        "B01001_027E",
                        "B01001_028E", 
                          "B01001_029E",
                          "B01001_030E",
                          "B01001_031E",
                          "B01001_032E",
                          "B01001_033E",
                          "B01001_034E",
                          "B01001_035E",
                          "B01001_036E",
                          "B01001_037E",
                          "B01001_038E",
                          "B01001_039E",
                          "B01001_040E",
                          "B01001_041E",
                          "B01001_042E",
                          "B01001_043E",
                          "B01001_044E",
                          "B01001_045E",
                          "B01001_046E",
                          "B01001_047E",
                          "B01001_048E",
                          "B01001_049E"), {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01003_001M": "Population_ME",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "B08133_001E": "Time to work",
                                      "B08008_004E": "Worked outside home",
                                      "B08006_002E": "Car, truck, van to work",
                                      "B08006_008E": "Public transit to work",
                                      "B08006_014E": "Biked to work",
                                      "B08006_015E": "Walked to work",
                                      "B08006_017E": "Worked at home",
                                      "B06010_011E": "Income over $75K",
                                      "B01001_003E": "Male Under 5 years",
                                      "B01001_004E": "Male 5-9 years",
                                      "B01001_005E": "Male 10-14 years",
                                      "B01001_006E": "Male 15-17 years", 
                                      "B01001_007E": "Male 18-19 years", 
                                      "B01001_008E": "Male 20 years", 
                                      "B01001_009E": "Male 21 years",
                                      "B01001_010E": "Male 22-24 years",
                                      "B01001_011E": "Male 25-29 years",
                                      "B01001_012E": "Male 30-34 years",
                                      "B01001_013E": "Male 35-39 years",
                                      "B01001_014E": "Male 40-44 years",
                                      "B01001_015E": "Male 45-49 years",
                                      "B01001_016E": "Male 50-54 years",
                                      "B01001_017E": "Male 55-59 years",
                                      "B01001_018E": "Male 60-61 years",
                                      "B01001_019E": "Male 62-64 years",
                                      "B01001_020E": "Male 65-66 years",
                                      "B01001_021E": "Male 67-69 years",
                                      "B01001_022E": "Male 70-74 years",
                                      "B01001_023E": "Male 75-79 years",
                                      "B01001_024E": "Male 80-84 years",
                                      "B01001_025E": "Male 85 years plus",
                                      "B01001_027E": "Female Under 5 years",
                                      "B01001_028E": "Female 5-9 years",
                                      "B01001_029E": "Female 10-14 years",
                                      "B01001_030E": "Female 15-17 years", 
                                      "B01001_031E": "Female 18-19 years", 
                                      "B01001_032E": "Female 20 years", 
                                      "B01001_033E": "Female 21 years",
                                      "B01001_034E": "Female 22-24 years",
                                      "B01001_035E": "Female 25-29 years",
                                      "B01001_036E": "Female 30-34 years",
                                      "B01001_037E": "Female 35-39 years",
                                      "B01001_038E": "Female 40-44 years",
                                      "B01001_039E": "Female 45-49 years",
                                      "B01001_040E": "Female 50-54 years",
                                      "B01001_041E": "Female 55-59 years",
                                      "B01001_042E": "Female 60-61 years",
                                      "B01001_043E": "Female 62-64 years",
                                      "B01001_044E": "Female 65-66 years",
                                      "B01001_045E": "Female 67-69 years",
                                      "B01001_046E": "Female 70-74 years",
                                      "B01001_047E": "Female 75-79 years",
                                      "B01001_048E": "Female 80-84 years",
                                      "B01001_049E": "Female 85 years plus",

                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})

# Add in Poverty Rate (Poverty Count / Population)
census_pd["Poverty Rate"] = census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Add in Avg.Time to work (Time to work / Worked outside home)
# census_pd["Avg. Time to Work"] = census_pd["Time to work"].astype(int) / census_pd["Worked outside home"].astype(int)

# Final DataFrame
census_pd = census_pd[["Zipcode", "Population","Population_ME", "Median Age", "Household Income",
                       "Per Capita Income", "Income over $75K", "Poverty Count", "Poverty Rate", "Time to work","Worked outside home",  
                       "Car, truck, van to work",
                        "Public transit to work", 
                       "Biked to work",
                        "Walked to work",
                        "Worked at home",
                        "Male Under 5 years",
                        "Male 5-9 years",
                        "Male 10-14 years",
                        "Male 15-17 years", 
                        "Male 18-19 years", 
                        "Male 20 years", 
                        "Male 21 years",
                        "Male 22-24 years",
                        "Male 25-29 years",
                        "Male 30-34 years",
                        "Male 35-39 years",
                        "Male 40-44 years",
                        "Male 45-49 years",
                        "Male 50-54 years",
                        "Male 55-59 years",
                        "Male 60-61 years",
                        "Male 62-64 years",
                        "Male 65-66 years",
                        "Male 67-69 years",
                        "Male 70-74 years",
                        "Male 75-79 years",
                        "Male 80-84 years",
                        "Male 85 years plus",
                        "Female Under 5 years",
                        "Female 5-9 years",
                        "Female 10-14 years",
                        "Female 15-17 years", 
                        "Female 18-19 years", 
                        "Female 20 years", 
                        "Female 21 years",
                        "Female 22-24 years",
                        "Female 25-29 years",
                        "Female 30-34 years",
                        "Female 35-39 years",
                        "Female 40-44 years",
                        "Female 45-49 years",
                        "Female 50-54 years",
                        "Female 55-59 years",
                        "Female 60-61 years",
                        "Female 62-64 years",
                        "Female 65-66 years",
                        "Female 67-69 years",
                        "Female 70-74 years",
                        "Female 75-79 years",
                        "Female 80-84 years",
                        "Female 85 years plus"]]

# Visualize
print(len(census_pd))
census_pd.tail()

33120

,Zipcode,Population,Population_ME,Median Age,Household Income,Per Capita Income,Income over $75K,Poverty Count,Poverty Rate,Time to work,...,Female 50-54 years,Female 55-59 years,Female 60-61 years,Female 62-64 years,Female 65-66 years,Female 67-69 years,Female 70-74 years,Female 75-79 years,Female 80-84 years,Female 85 years plus
33115,00979,15019.0,1051.0,49.6,35251.0,28053.0,NaN,2613.0,0.173980,184560.0,...,486.0,924.0,227.0,448.0,265.0,259.0,457.0,488.0,380.0,287.0
33116,00982,14874.0,1009.0,43.0,25362.0,13301.0,NaN,5189.0,0.348864,135730.0,...,573.0,600.0,235.0,361.0,142.0,226.0,447.0,399.0,430.0,357.0
33117,00983,38533.0,1890.0,40.4,27612.0,13459.0,NaN,12301.0,0.319233,395335.0,...,1225.0,1322.0,356.0,746.0,377.0,763.0,1433.0,844.0,505.0,723.0
33118,00985,33320.0,1431.0,41.0,24091.0,13108.0,NaN,11302.0,0.339196,338155.0,...,1218.0,1010.0,456.0,689.0,609.0,826.0,1202.0,831.0,559.0,395.0
33119,00987,58705.0,2031.0,37.6,31758.0,15522.0,NaN,15396.0,0.262260,775375.0,...,2245.0,1920.0,610.0,1061.0,607.0,1045.0,1371.0,824.0,437.0,793.0

In [17]:
# Save as a csv
# Note to avoid any issues later, use encoding="utf-8"
census_pd.to_csv("census_data_age.csv", encoding="utf-8", index=False)
print('done')

done

In [18]:
#